sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t djelin00/fib-test -f ./client/Dockerfile.dev ./client 
script:
  - docker run -e CI=true djelin00/fib-test npm test  
after_success:
  - docker build -t djelin00/fib-client ./client 
  - docker build -t djelin00/fib-nginx ./nginx 
  - docker build -t djelin00/fib-server ./server
  - docker build -t djelin00/fib-worker ./worker 
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin 
  - docker push djelin00/fib-client
  - docker push djelin00/fib-nginx
  - docker push djelin00/fib-server
  - docker push djelin00/fib-worker
  